package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/jonniespratley/jps_go_app/models"
	"github.com/pkg/errors"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Theme)
// DB Table: Plural (themes)
// Resource: Plural (Themes)
// Path: Plural (/themes)
// View Template Folder: Plural (/templates/themes/)

// ThemesResource is the resource for the Theme model
type ThemesResource struct {
	buffalo.Resource
}

// List gets all Themes. This function is mapped to the path
// GET /themes
func (v ThemesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	themes := &models.Themes{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Themes from the DB
	if err := q.All(themes); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, themes))
}

// Show gets the data for one Theme. This function is mapped to
// the path GET /themes/{theme_id}
func (v ThemesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Theme
	theme := &models.Theme{}

	// To find the Theme the parameter theme_id is used.
	if err := tx.Find(theme, c.Param("theme_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, theme))
}

// New renders the form for creating a new Theme.
// This function is mapped to the path GET /themes/new
func (v ThemesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.Theme{}))
}

// Create adds a Theme to the DB. This function is mapped to the
// path POST /themes
func (v ThemesResource) Create(c buffalo.Context) error {
	// Allocate an empty Theme
	theme := &models.Theme{}

	// Bind theme to the html form elements
	if err := c.Bind(theme); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(theme)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, theme))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Theme was created successfully")

	// and redirect to the themes index page
	return c.Render(201, r.Auto(c, theme))
}

// Edit renders a edit form for a Theme. This function is
// mapped to the path GET /themes/{theme_id}/edit
func (v ThemesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Theme
	theme := &models.Theme{}

	if err := tx.Find(theme, c.Param("theme_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, theme))
}

// Update changes a Theme in the DB. This function is mapped to
// the path PUT /themes/{theme_id}
func (v ThemesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Theme
	theme := &models.Theme{}

	if err := tx.Find(theme, c.Param("theme_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Theme to the html form elements
	if err := c.Bind(theme); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(theme)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, theme))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Theme was updated successfully")

	// and redirect to the themes index page
	return c.Render(200, r.Auto(c, theme))
}

// Destroy deletes a Theme from the DB. This function is mapped
// to the path DELETE /themes/{theme_id}
func (v ThemesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Theme
	theme := &models.Theme{}

	// To find the Theme the parameter theme_id is used.
	if err := tx.Find(theme, c.Param("theme_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(theme); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Theme was destroyed successfully")

	// Redirect to the themes index page
	return c.Render(200, r.Auto(c, theme))
}
